### ISSUE TITLE
QBASIC port?

### ISSUE THREAD

**Issue by djberube** [Spitball-Sessions/TicTacToe#1]
Are there any plans to port this to QBASIC? 

I'm happy to open a PR to get the ball rolling if there's interest.

Have a great day,

David Berube

**Comment by Spitball-Sessions** [comment]
> Are there any plans to port this to QBASIC?
> 
> I'm happy to open a PR to get the ball rolling if there's interest.
> 
> Have a great day,
> 
> David Berube
 
Hello David,
please see the branch repo:
https://github.com/Spitball-Sessions/TicTacToe/tree/qbasic
